### ISSUE TITLE
潜在的性能问题

### ISSUE THREAD

**Issue by lolligun** [lolligun/ModBahuang#10]
目前每次加载资源都会用 `Instantiate` 来创建个新的 `GameObject`。理论上来说，一次拍卖会如果来 500 人，每个人的立绘都被修改过，那么打开一次 NPC 列表将会在游戏里创建大约 500 * 10 = 5000 个新的 `GameObject`。这应该是不可接受的。
不过我在 60 人的主城，只改了 10 多几件衣服的情况下，并有没发现和不加 Mod 时有什么明显的性能区别。

**Comment by lolligun** [comment]
每次都从硬盘的文件上重新创建材质会导致严重性能问题（加载一个角色要大约 2 秒）
https://github.com/lolligun/ModBahuang/blob/511e33d0dd7c44043dfc341c08193dee0240cb8d/Hylas/Hylas.cs#L155

**Comment by lolligun** [comment]
在 b8cda20240b969e6c49a1aaa392ce8445d49dfdc 增加了预载入，解决了游戏中的卡顿问题。不过由于加载过程提前，导致每次进入游戏最坏要 50 秒 (300 图，500 MB)，即使是在一般情况下也需要大约 20 秒 (200 图, 200 MB 左右)。
能想到的优化方案有：
- 并行
- 打包（将文件夹打包成更为读取优化的格式），不过这又会导致无法动态修改。

**Comment by cai-chenghui** [comment]
有没有可能在首次加载的时候创建缓存，把20秒平均分配到游戏过程中应该能提升体验。
扫描文件 -> 路径加入字典默认值为null -> 访问为null则进行Update

**Comment by lolligun** [comment]
> 有没有可能在首次加载的时候创建缓存，把20秒平均分配到游戏过程中应该能提升体验。

应该是可以，但我想不到很好的方案。
> 扫描文件 -> 路径加入字典默认值为null -> 访问为null则进行Update

问题在于在加载 NPC 界面时需要一次进行大量 Update，这样第一次点开界面还是会卡。

**Comment by cai-chenghui** [comment]
资源加载只允许在主线程调用，所以理论上多线程GG了。就是不知道MelonLoader支不支持协程

**Comment by lolligun** [comment]
现在的问题在于实际上因为我没有 benchmark 过，所以没有确定性能瓶颈在哪。@LangYueMc 之前在群里提到过不过我不清楚他的进展。所以如果想要解决这个问题，先进行 bench 再根据结果提出解决方案会比较好。

**Comment by lolligun** [comment]
发现了这个 https://github.com/LangYueMc/Butian

**Comment by cai-chenghui** [comment]
不知道该怎么附加调试 Mod 所以用 StopWatch 做了个简单的计数
![image](https://user-images.githubusercontent.com/26640946/121377498-f80e2d00-c974-11eb-915c-f25e690da4a7.png)
结果比较悲剧，看起来大部分的时间开销实际上都在 `ImageConversion::LoadImage` 和 `Sprite::Create`
希望能提供一些参考

**Comment by lolligun** [comment]
> 看起来大部分的时间开销实际上都在 ImageConversion::LoadImage 和 Sprite::Create

和我的猜测差不多。目前应该没什么很好的优化方法。

**Comment by lolligun** [comment]
关闭。请使用补天 (https://github.com/LangYueMc/Butian)
