### ISSUE TITLE
Hylas前发不能替换

### ISSUE THREAD

**Issue by cmlibo** [lolligun/ModBahuang#11]
**问题描述**
前发的规则跟其他的不一样，其他都是从101开始的，前发是从1201开始的，代码未做处理，导致报错了，无法生效，麻烦修正一下，好多年没写过C#，已经不会改了

**Comment by lolligun** [comment]
这种情况已经考虑到了，自带的实例里在前发的文件夹内有一个txt文件，你复制到对应的文件夹就好。

**Comment by lolligun** [comment]
https://github.com/lolligun/ModBahuang/blob/511e33d0dd7c44043dfc341c08193dee0240cb8d/Hylas/Worker.cs#L29

**Comment by cmlibo** [comment]
> https://github.com/lolligun/ModBahuang/blob/511e33d0dd7c44043dfc341c08193dee0240cb8d/Hylas/Worker.cs#L29
厉害了，原来是这样用的
这段代码一开始没看懂，

然后自己加了段代码。
if (root.IndexOf("HairFront") > -1) {
                    templateId = "1201";
                }
环境搞了半天，先装net core sdk，win10 现在都是 v4.8，你写的v4.7.2，改成v4.8，发现也跑不起来，才发现没有编译环境，又装了ndp48-devpack-enu.exe。折腾了将近一个小时才打包成功
