### ISSUE TITLE
sprite.json 中的size如果不正确的话会引发异常, 之后改正确也无法恢复了

### ISSUE THREAD

**Issue by Unintendedz** [lolligun/ModBahuang#12]
**先行检查**
在你提交问题之前请先进行如下自检：
- [x] 已安装了 [.NET Framework 4.8 Runtime](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer) 以及 [Microsoft Visual C++ 2015-2019 Re-distributable](https://aka.ms/vs/16/release/vc_redist.x64.exe)
- [x] 使用的 `MelonLoader` 是在 [3DM Mod站下载的](https://mod.3dmgame.com/mod/173451)（其他地方下载的 `MelonLoader` 不打算支持）。
- [x] 游戏路径中不存在空格。请确保游戏没有被安装在 `Program Files`。
- [x] 在每次游戏更新后都运行了 `installer.exe`

**问题描述**
sprite.json 中的size如果不正确的话会引发异常, 只能重新上游戏解决

**问题复现**
请详细的写出能够重现该问题的具体步骤：
1. 进入新建角色界面
2. 将一张分辨率和sprite.json中不同的图片复制到`鬼谷八荒\Mods\Hylas\Woman\Body\101`
3. 将其改名为image.png
4. 切换两三次服装

**预期行为**
正确显示, 即使位置有问题(或者因为分辨率不对应, 不显示也行. 但是这个异常不能恢复只能重新上游戏)

**问题截图**
![ScreenShot_2021-04-10_14-13-04](https://user-images.githubusercontent.com/64687143/114260359-e6f18000-9a06-11eb-81ae-fba3db7eed17.png)

此后即使切换回正确的图片, 或者将sprite.json中的分辨率设置为图片对应的分辨率, 也无法恢复正常
人物的1号衣服依然不会显示
切换其他服饰也会提示
```
[ERROR] System.NullReferenceException: Object reference not set to an instance of an object
```
必须重新上游戏才能解决

**Latest.log**

[Latest.log](https://github.com/lolligun/ModBahuang/files/6289328/Latest.log)

**运行环境**
操作系统：Windows 10 20H1
问题 Mod：Hylas
鬼谷八荒版本：0.8.2015

**额外说明**

**Comment by lolligun** [comment]
和 #9 重复，已在 0.3.1 修复。
