### ISSUE TITLE
2017版本 生成地图的时候 创建的全是女性 但是开第二地图开始 会刷少量男性

### ISSUE THREAD

**Issue by kotoriww** [lolligun/ModBahuang#13]
2017版本 在开第二图会刷新少量男性

**问题截图**
如果可以，请贴出能够显示出问题的详细截图。
![image](https://user-images.githubusercontent.com/33814719/114281346-77b07600-9a70-11eb-84aa-d973633ea53e.png)

**Comment by lolligun** [comment]
在 0.8.2017 之前的版本会出现这种情况吗

**Comment by kotoriww** [comment]
> 在0.8.2017之前的版本会出现这种情况吗
之前没用过 2017版本才开始用  我试了一下  第一个图的时候都是女性 后面开图之后就会刷少量男性  基本在80-100个 我杀了或者改存档寿命改到死  下次还会刷出来

**Comment by lolligun** [comment]
我检查了游戏，没有发现有什么问题。并且问了一下其他人，也没有人遇到相同的问题。
因此目前我并不能确定问题所在，也不清楚如何修复。
你确定 Mod 是在正常工作的吗？（你再新建一个存档，依然全部都是女性 NPC 吗？）因为据我所知，在新刷新 NPC 时出现男性应该只有在 Mod 被卸载后才会出现。

**Comment by kotoriww** [comment]
好 我下班在测试一下
