### ISSUE TITLE
Hylas v0.3.2.不能替换2D小人头发，求解决

### ISSUE THREAD

**Issue by zhou19800908** [lolligun/ModBahuang#14]
如图：
![20210411220707](https://user-images.githubusercontent.com/66667509/114308887-f0b6d880-9b17-11eb-908e-fd5daf9eaf7c.png)
![20210411220724](https://user-images.githubusercontent.com/66667509/114308904-f7dde680-9b17-11eb-86ef-e36d43bcc5ae.png)

**Comment by lolligun** [comment]
模板是用来填写的，不是用来删除的。你连 log 都不贴，问题要怎么才能解决呢？
不过盲猜这个问题和 f6e125537672cb569d1307985b5dd1e482776c5b 有关，应该修好了才对。

**Comment by lolligun** [comment]
关闭。请使用补天 (https://github.com/LangYueMc/Butian)
