### ISSUE TITLE
在读取Hylas文件夹时报错

### ISSUE THREAD

**Issue by YPAtob** [lolligun/ModBahuang#26]
游戏开始时卡住
![image](https://user-images.githubusercontent.com/21964271/123550727-879f4280-d7a1-11eb-8247-a238b16d0804.png)

异常
![image](https://user-images.githubusercontent.com/21964271/123550381-c59b6700-d79f-11eb-9840-245ac050faa8.png)

问题代码出现在Utils.cs
![image](https://user-images.githubusercontent.com/21964271/123550416-ec599d80-d79f-11eb-9af5-45b366067079.png)

修复代码
![image](https://user-images.githubusercontent.com/21964271/123550426-f9768c80-d79f-11eb-8caf-03f468cf179f.png)

**Comment by lolligun** [comment]
Good catch.

**Comment by lolligun** [comment]
关闭。请使用补天 (https://github.com/LangYueMc/Butian)
