### ISSUE TITLE
一般玩家的使用体验

### ISSUE THREAD

**Issue by lolligun** [lolligun/ModBahuang#3]
目前 Mod 对一般玩家来说使用起来其实非常复杂(实际上我自己也觉得很复杂)，这里列举了一些等待修复的问题点：
- [ ] 安装繁琐
- [ ] 手动更新
- [ ] 依赖混乱
- [ ] 报错不明

#### 安装繁琐
不论安装 MelonLoader 竟然需要下载运行库这种问题，Mod 安装成功竟然不能解压即用，而是需要好几个步骤
1. 运行 installer
2. 打开游戏(因为要让 Melon 生成文件夹)
3. 放入 Mod
4. 再次打开游戏
5. 如果要用 Villain 还要重新打开游戏，放入 patch

这些步骤实在难以忍受，并且实际上都是可以避免的。如把 installer 解密的功能集成到 Melon 里，使 Villain 不自动 Dump 配置，分发时直接带上 Mods 文件夹等。
#### 手动更新
这个和前面的是一样的，辛辛苦苦安装成功竟然每次游戏更新还要再弄一次，而且就算步骤错了竟然还不会报错？！
#### 依赖混乱
发个 Mod 还要去别的地方下载一堆东西，并且有些 Dll 的名字、id还冲突，根本乱七八糟。
#### 报错不明
首先报错是英文的就有问题，大部分人连中文报错都跳过不看，谁有功夫去看英文报错呢，根本看不懂。为什么我装完会提示 `blahblah` 呢？解决方法就只有重装。

---
导致以上这些问题的其中一个原因在于从一开始这些 Mod 都只是给我自己用的，根本原则是：能用就行。

**Comment by buzhidaozaiganmadetuanzi** [comment]
或者再自下而上做个窗口用来管理mod？那岂不是和创意工坊一样了，还是说等创意工坊？

**Comment by buzhidaozaiganmadetuanzi** [comment]
0.2使用了之后之前的人物衣服好像大部分都偏移了

**Comment by buzhidaozaiganmadetuanzi** [comment]
偏移了

**Comment by lolligun** [comment]
> 0.2使用了之后之前的人物衣服好像大部分都偏移了

不在这个的范围内，有问题可以去提新的 Issue。不过你说的我没遇到。

> 或者再自下而上做个窗口用来管理mod？那岂不是和创意工坊一样了，还是说等创意工坊？

等创意工坊开了再看吧，目前没有改的欲望。

**Comment by Zephyr-666** [comment]
运行游戏并没有生成相应的文件夹是什么原因呢，MelonLoader的控制台显示Villain v0.2.1 mod已经加载

**Comment by lolligun** [comment]
> 运行游戏并没有生成相应的文件夹是什么原因呢，MelonLoader的控制台显示Villain v0.2.1 mod已经加载

有问题请 _新建一个 Issue_，不要在这里问！
提 Issue 请给出对应的 log 文件，我又不会魔法！
