### ISSUE TITLE
Latest update broken villain.

### ISSUE THREAD

**Issue by NamelessButler** [lolligun/ModBahuang#30]
Hello, latest game update (0.8.3015.266) broke villain.
Melon loader report below.
![image](https://user-images.githubusercontent.com/50148645/127744014-2398c655-61ae-4a6e-a9fc-71159a70422d.png)

Thnks for your hard work.

**Comment by NamelessButler** [comment]
After a fresh MelonLoader + Villain new build up files it was fixed.

**Comment by Flincat** [comment]
> After a fresh MelonLoader + Villain new build up files it was fixed.

i am still having this issue though, where do I find latest versions of melonloader and villain dll for a fresh installation? It's been a while since I played.

**Comment by Flincat** [comment]
i have right now exact same issue as you had before
