### ISSUE TITLE
Villain does not apply new record for version 3017

### ISSUE THREAD

**Issue by rfcclub** [lolligun/ModBahuang#31]
Looks like it does not apply new record into game, for example we can create a patch_RoleDress with a RoleDress.json as follow

[
  {
    "id": 58109,
    "dressID": 209,
    "sex": 2,
    "type": "yifu",
    "colorGroup": 58109,
    "color": "7983A6",
    "name": "common_yifu",
    "flag": "0",
    "gamerFlag": "0",
    "flagDesc": "0",
    "beauty": 50,
    "weight": 100
  }
]

Game does not display this extra clothes.
It can merge current existing conf but not apply new conf. There are 2 new fields in ConfBase, but I don't know their effect
obj.isModExtend and obj.isVariant. I tried to put obj.isModExtend=true in 
`public ConfBaseItem Construct()` but seems it didn't work.

**Comment by waterpop** [comment]
> obj.isModExtend and obj.isVariant

It seems like caused by the new development of the official mod creator(see https://t.bilibili.com/558374949970215650). I don't know whether we should continue to update on villain, or it's time to wait for the official support.
Thanks!

**Comment by rfcclub** [comment]
Yeah you're right, seems it's the preparation for workshop release. 
Btw based on your comment I have found out that it's gonna work if we use official method like `conf.AddItem` instead of adding conf through List method like `conf.allConfBase.Add` . 
Hope the fix can still works 'till the game workshop release.
