### ISSUE TITLE
更新0.30后无法用人物立绘了

### ISSUE THREAD

**Issue by mengxinlian0712** [lolligun/ModBahuang#9]
更新就不行了，只能显示一次，一次显示完就会读取原来的resource文件。

**Comment by lolligun** [comment]
你能解释的更清楚一点吗？
1. 请贴出你的 `Latest.log` 文件（在`鬼谷八荒\MelonLoader`）
2. 请给出更具体的复现步骤。你进行了什么操作？期待什么行为？如果给截个图就更好了。

**Comment by mengxinlian0712** [comment]
[Latest.log](https://github.com/lolligun/ModBahuang/files/6279848/Latest.log)

图片我也无法做成gif给你，就是修改着修改着他就变回原来的resource文件的衣服再也变不回来，要重新打开游戏才能用

**Comment by lolligun** [comment]
应该已在v0.3.1 a5d73d959a87b34a11cffe44510095d11ba299b8 修复，等今天游戏更新就会发
